### PR TITLE
708 - fix console warning in disable connections

### LINKED ISSUE #708: Fix Console Warning for Disable Connection
### Bug Description

Enabling/disabling connections from the UI is functional, but you get the following console warning:

```
next-dev.js?3515:32 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at DisableConnectionModal (webpack-internal:///./src/features/datastore-connections/DisableConnectionModal.tsx:24:29)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at VisualElementHandler (webpack-internal:///./node_modules/framer-motion/dist/es/motion/utils/VisualElementHandler.mjs:13:42)
    at MotionComponent (webpack-internal:///./node_modules/framer-motion/dist/es/motion/index.mjs:50:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at eval (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js:819:25)
    at DefaultPortal (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/portal/dist/chakra-ui-portal.esm.js:105:36)
    at Portal (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/portal/dist/chakra-ui-portal.esm.js:184:28)
    at Menu (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js:717:24)
    at ConnectionMenu (webpack-internal:///./src/features/datastore-connections/ConnectionMenu.tsx:21:29)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at eval (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.esm.js:414:25)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at ConnectionGridItem (webpack-internal:///./src/features/datastore-connections/ConnectionGridItem.tsx:95:30)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at eval (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.esm.js:455:20)
    at eval (webpack-internal:///./node_modules/@fidesui/react/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.esm.js:753:23)
```

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by eastandwestwind**
# Purpose
Fix console warning in disable connections

# Changes
- Removes unneeded code in disable connection

# Checklist
- [x] Update [`CHANGELOG.md`](https://github.com/ethyca/fidesops/blob/main/CHANGELOG.md) file
  - [x] Merge in main so the most recent `CHANGELOG.md` file is being appended to
  - [x] Add description within the `Unreleased` section in an appropriate category. Add a new category from the list at the top of the file if the needed one isn't already there.
  - [x] Add a link to this PR at the end of the description with the PR number as the text. example: [#1](https://github.com/ethyca/fidesops/pull/1)
- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md).
- If docs updated (select one):
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

# Ticket

Fixes #708

### CODE REVIEW

File: clients/admin-ui/src/features/datastore-connections/DisableConnectionModal.tsx [hunk 1]
```diff
@@ -38,15 +38,13 @@ const DisableConnectionModal: React.FC<DataConnectionProps> = ({
...
     const shouldDisable = !disabled;
-    return patchConnection({
+    patchConnection({
       key: connection_key,
       name,
       disabled: shouldDisable,
       access: access_type,
       connection_type,
     })
-      .unwrap()
```
Comment (TheAndrewJackson) [inline clients/admin-ui/src/features/datastore-connections/DisableConnectionModal.tsx:48]: Does the modal still close once the request finishes?

Comment (eastandwestwind) [reply clients/admin-ui/src/features/datastore-connections/DisableConnectionModal.tsx:48]: Yup, it still closes automatically once the request completes

Comment (TheAndrewJackson) [reply clients/admin-ui/src/features/datastore-connections/DisableConnectionModal.tsx:48]: That's great. So was the issue was calling the `onClose` function after the modal had closed?

**Review by pattisdr — APPROVED** [review]
